server:
  port: 9001

spring:
  application:
    name: @artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.17.102:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    stream:
      binders:
        myRabbit:
          #消息中间件类型
          type: rabbit
          #rabbitmq连接信息配置
          environment:
            spring:
              rabbitmq:
                host: 192.168.17.202
                port: 5672
                username: root
                password: 123456
                virtual-host: /
      #添加消息发送相关信息，发送消息路由键默认为destination，默认会创建topic类型的exchange
      bindings:
        msgChannel:
          destination: account-change
          binder: myRabbit
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shopping.entities

eureka:
  client:
    #表示将本服务注册进eureka server 默认为true
    register-with-eureka: true
    #是否从Eureka Server抓取已有的注册信息，默认为true。
    #单节点无所谓，集群必须要设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://192.168.17.101:7001/eureka/,http://192.168.17.103:7002/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #eureka客户端向服务端发送心跳时间间隔，默认为30秒
    #lease-renewal-interval-in-seconds: 1
    #eureka在收到最后一次心跳后等待时间，超时后剔除服务。默认为90秒
    #lease-expiration-duration-in-seconds: 2

